<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="msd700_prototype">
    <!-- Chassis Property -->
    <xacro:property name="chassis_length" value="0.3"/>
    <xacro:property name="chassis_width" value="0.2"/>
    <xacro:property name="chassis_height" value="0.184"/>

    <!-- Wheel Property -->
    <xacro:property name="wheel_radius" value="0.054"/>
    <xacro:property name="wheel_width" value="0.02"/>

    <!-- Includes -->
    <xacro:include filename="$(find msd700_description)/urdf/common/inertials.xacro"/>
    <xacro:include filename="$(find msd700_description)/urdf/common/materials.xacro"/>
    <xacro:include filename="$(find msd700_description)/urdf/common/wheel.urdf.xacro"/>
    <xacro:include filename="$(find msd700_description)/urdf/sensors/2d_lidar.urdf.xacro"/>
    <xacro:include filename="$(find msd700_description)/urdf/sensors/imu.urdf.xacro"/>

    <link name="base_link" />

    <joint name="base_to_chassis_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="chassis_link"/>
    </joint>

    <link name="chassis_link">
        <visual>
            <origin xyz="-0.15 -0.1 -0.092" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://msd700_description/meshes/msd700_without_arm.stl" scale="0.001 0.001 0.001" />
            </geometry>
            <material name="grey"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}" />
            </geometry>
        </collision>
        <xacro:box_inertial m="1" w="${chassis_width}" l="${chassis_length}" d="${chassis_height}" xyz="0 0 0" rpy="0 0 0"/>
    </link>

    <gazebo reference="chassis_link">
        <material>Gazebo/Grey</material>
    </gazebo>

    <xacro:include filename="$(find msd700_description)/urdf/gazebo/msd700_prototype.gazebo.xacro"/>

    <xacro:add_wheel prefix="bl_wheel" radius="${wheel_radius}" thickness="${wheel_width}" xyz="-${chassis_length/2} ${chassis_width/2 + wheel_width/2} -${chassis_height/2}" parent="chassis_link"/>
    <xacro:add_wheel prefix="br_wheel" radius="${wheel_radius}" thickness="${wheel_width}" xyz="-${chassis_length/2} -${chassis_width/2 + wheel_width/2} -${chassis_height/2}" parent="chassis_link"/>
    <!-- <xacro:add_wheel prefix="mid_wheel" radius="${wheel_radius}" thickness="${wheel_width}" xyz="${chassis_length/2} 0 -${chassis_height/2}" parent="chassis_link"/> -->
    <xacro:add_wheel prefix="fr_wheel" radius="${wheel_radius}" thickness="${wheel_width}" xyz="${chassis_length/2} -${chassis_width/2 + wheel_width/2} -${chassis_height/2}" parent="chassis_link"/>
    <xacro:add_wheel prefix="fl_wheel" radius="${wheel_radius}" thickness="${wheel_width}" xyz="${chassis_length/2} ${chassis_width/2 + wheel_width/2} -${chassis_height/2}" parent="chassis_link"/>

    <xacro:add_2d_lidar prefix="lidar" topic="scan" parent="chassis_link" x="0" y="0" z="${chassis_height/2}" rpy="0 0 0"/>

    <!-- <xacro:add_imu prefix="imu" topic="imu" parent="chassis_link" xyz="0 0 0.02" rpy="0 0 0"/> -->
    

</robot>
